Rothem 예약 시스템 개발 및 유지보수
Team-Space-kbu/haram-backend pull request #12
Opened 2023-04-14 07:50 UTC by Msangwool

## Rothem 예약 시스템을 위한 프로그램입니다.

### Entity
- Room - 방 정보
- Reservation - 예약 정보

**DTO**
- ReservationDto - 예약에 필요한 Dto 입니다.

### Service &  Repositry
1. RoomRepository - 로뎀 방 정보를 저장 및 관리합니다.
2. ReservationRepository - 예약 정보를 저장 및 관리합니다.
3. RothemService - 로뎀 예약 시스템을 전반적으로 관리하고 필수 기능을 제공합니다.

위 세개의 핵심 기능은 interfcae입니다. 각 1, 2 번에 대한 구현체는 Memory 전용으로 하나씩 구현했으며, 3번은 RothemServiceImpl 을 구현해놓았습니다.

### Controller
- getAllRooms[ROLE_USER] - 사용자가 방 정보를 확인한다.
- getReservations[ROLE_USER] - 넘겨받는 사용자의 예약 정보를 확인한다.
- reserveRooms[ROLE_USER] - 방을 예약한다.

- listReservations[ROLE_ADMIN] - 현재 예약 요청중인 리스트를 볼 수 있다.
- listReservation[ROLE_ADMIN] - 특정 방에 대해 현재 예약 요청중인 리스트를 볼 수 있다.
- permitReservations[ROLE_ADMIN] - 현재 요청중인 예약의 상태를 true 로 변경한다.

### Test
각 Controller에 대한 Test 코드가 작성되어 있습니다. 실행하지 않고, API 에 대해 요청해야 하기 때문에, MockMvc를 주입받아 perform 메서드를 통해 Http 요청을 Test 했습니다.

- setUp - @BeforeEach 로 모든 테스트 코드 실행 전에 한번씩 실행되는 초기화 코드입니다.
- allFunction - Rothem 서비스에서 가장 기본시 되는 로직을 Test 한 코드입니다.
  - 1. 사용자는 빈 방 조회
  - 2. 사용자가 예약 신청
  - 3. 관리자는 예약 리스트 확인
  - 4. 관리자는 예약 허용
  - 5. 바뀐 방 정보

2023-04-14 09:29 UTC, mookseong commented on src/main/java/com/space/haramspring/core/entity/users/Reservation.java
Entity파일이 user디렉토리 보단 rothem이란 디렉토리 만들어서 거기에 추가하시는게 좋게습니다.

2023-04-14 10:09 UTC, mookseong commented on src/main/java/com/space/haramspring/core/entity/users/Room.java
이 파일도 따로 Rothem 디렉토리 만드셔서 거기로 옮겨주세요~

2023-04-14 10:15 UTC, mookseong commented on src/main/java/com/space/haramspring/rothem/controller/RothemController.java
> +    @GetMapping("{userId}/reservations")
특정 사용자의 정보를 조회할때  `{userId}/reservations`보다는 `/reservations/{userId}`형식으로 하는게 좋아 보입니다.
그리고 `{userId}`통해 조회할 경우 다른 사용자의 아이디로 요청할 수 있는 문제가 발생할 수 있습니다. 토큰 정보로 사용자별 조회할 수 있도록 코드를 변경하는 것이 안전해 보입니다.

2023-04-14 10:16 UTC, mookseong commented on src/main/java/com/space/haramspring/rothem/controller/RothemController.java
> +    @GetMapping("/reservations/{roomId}/lists")
이코드 또한 토큰별에 있는 사용자 값을 통해 조회할 수 있도록 수정해주세요

2023-04-14 10:20 UTC, mookseong commented on src/main/java/com/space/haramspring/rothem/service/RothemServiceImpl.java
기능이 전체적으로 다 완성된 코드인가요?

2023-04-14 10:25 UTC, mookseong commented on src/main/java/com/space/haramspring/rothem/service/RothemService.java
방을 예약하고 조회하고 불러오는 것은 가능해 보이나, 방에 대한 상제 정보를 볼 수 있는 정보가 없어 보입니다.
기능이 필요해 보입니다.

2023-04-14 10:27 UTC, mookseong commented on src/main/java/com/space/haramspring/rothem/service/RothemServiceImpl.java
> +    public ResponseModel getAllRooms() {
코드의 의도는 보이나 여기서 특정 기간에 따라 확인할 수 있는 기능도 필요해보입니다.
지난 날자는 따로 조회할 수 있게 하거나  현재 예약중인 방만 확인할 수 있거나  기능이  필요해 보입니다.

2023-04-14 10:28 UTC, mookseong reviewed
기본 적인 기능은 어느정도 구현이 다 된거같은데 아직 다른 부과적인 기능은 없는거같습니다.
추가적으로 확인하고 수정이 필요해 보입니다.

2023-04-15 08:07 UTC, Msangwool commented on src/main/java/com/space/haramspring/core/entity/users/Reservation.java
그게 좋겠네요... 수정하겠습니다!!

2023-04-16 11:00 UTC, Msangwool commented on src/main/java/com/space/haramspring/rothem/controller/RothemController.java
> +    @GetMapping("{userId}/reservations")
토큰의 값과 @PathVariable 로 받아오는 아이디를 확인하는 작업이 필요하므로 처음부터 토큰 정보로 조회하는 방법이 더 좋아보이네요..! 수정하겠습니다.

2023-04-16 11:04 UTC, Msangwool commented on src/main/java/com/space/haramspring/rothem/controller/RothemController.java
> +    @GetMapping("/reservations/{roomId}/lists")
이는 관리자 계정만 허용된 기능입니다. hasRole("ADMIN") 을 통해 접근을 막을 수 있으므로 이 상태도 괜찮지 않을까요?

2023-04-16 14:40 UTC, mookseong commented on src/main/java/com/space/haramspring/rothem/controller/RothemController.java
> +    @GetMapping("/reservations/{roomId}/lists")
그렇게 진행하면 괜찮을것 같습니다.
만약 그렇게 진행된다면 Token 정보를 암호화 해서 진행해야할것 같습니다.

2023-04-16 14:41 UTC, mookseong commented on src/main/java/com/space/haramspring/rothem/controller/RothemController.java
> +    @GetMapping("/reservations/{roomId}/lists")
추가적으로 주석으로 관리자 관련된 기능은 주석을 추가적으로 작성부탁드립니다

2023-04-18 13:42 UTC, Msangwool commented
1. 주석 수정
2. 권한에 따른 controller 분할
3. 잘못된 url 요청 방지를 위한 토큰 기반 조회 서비스
4. 스케줄링 서버를 위한 기본 api 구성
5. entity 파일 이동

위와 같이 크게 5가지 수정했습니다.

2023-04-20 13:38 UTC, Msangwool commented on src/main/java/com/space/haramspring/rothem/service/RothemService.java
방 정보를 요청할 때, 모든 방의 예약 가능 여부를 알 수 있는 api 와 각 방에 대한 상세 정보를 확인하는 api 두개로 분리했습니다.

2023-04-21 06:11 UTC, mookseong requested changes
예약 기능을 제작을 하는데 고생하셨습니다.
현재 그럼 테스트 까지 진행했을때 문제는 없는건가요?

2023-04-21 14:28 UTC, Msangwool commented on src/main/java/com/space/haramspring/rothem/controller/RothemController.java
> +    @GetMapping("{userId}/reservations")
수정하다 보니 토큰 정보를 통해 정보를 조회하기 보다, @PathVariable 을 통해 받아온 아이디와 토큰의 아이디가 일치하는 경우 조회할 수 있도록 설계하는 것이 더 안전해보입니다.. ! 이렇게 설계하겠습니다!

2023-04-24 14:44 UTC, mookseong approved these changes
좋습니다. 테스트코드를 조금더 간결하게 작성하시면 좋을 것 같습니다. 
고생하셨습니다.

2023-04-25 05:21 UTC, merged