게시판 기능 설계 및 구현
Team-Space-kbu/haram-backend pull request #19
Opened 2023-05-08 11:01 UTC by Msangwool

## Package
게시글(Board), 댓글(Comment), 대댓글(NestedComment) 총 세개의 엔티티를 구성하고, 이를 위한 각각의 Service 와 Repository 를 구현하였습니다.

### Entity
- Board 
- Comment 
- NestedComment 

### Service
- BoardService 
- CommentService 
- NestedCommentService 

### Repository
- BoardRepository
- CommentRepository
- NestedCommentRepository

### Controller 
- BoardController (/v1/boards)
- CommentController (/v1/comments)
- NestedCommentController (/v1/nestedComments)

### Dto
- BoardDto 
- BoardDeleteDto
- BoardUploadDto
- BoardUpdateDto
- CommentDto 
- CommentDeleteDto
- CommentUploadDto
- CommentUpdateDto
- NestedCommentDto 
- NestedCommentDeleteDto
- NestedCommentUploadDto
- NestedCommentUpdateDto

Dto는 각 기능별로 설계했습니다. 추후 변경시에 추가될 필드들을 생각하여 모두 분리했습니다.

2023-05-08 13:52 UTC, mookseong commented on src/main/java/com/space/haramspring/board/controller/CommentController.java
> +        return ResponseEntity.ok().body(commentService.createComments(commentUploadDto));
Response모델이 기본 ResponseEntity으로 지정해서 한 이유가 있을까요?

2023-05-08 14:02 UTC, mookseong commented on src/main/java/com/space/haramspring/board/service/BoardServiceImpl.java
> +        );
동작하는 것에 해서는 문제는 없어 보이지만, Repository와 Service간 구분이 없는것 같습니다. 댓글과 게시판과 의존하는관계는 맞지만 이렇게 진행될경우 추후에 코드를 변경할 경우 복잡한 구조를 가지게 될 것 같습니다. 게시판과 댓글을 서비스를 분리시키고 거기에 구조패턴을 적용하는게 좋을것 같네요

2023-05-08 14:05 UTC, mookseong requested changes
전반적인 게시판 기능을 잘수행하는것  같습니다. 하지만 서비스와 레포지토리간 코드 연결이 그물처럼 뭉쳐 있는 느낌이 큽니다. 추후 유지관리에 있어서 어려움이 보입니다. 구조 패턴을 통해 구조를 개선해보는게 어떤가요

2023-05-09 05:50 UTC, Msangwool commented
게시판이 지워지면 해당 게시판의 댓글이 모두 지워져야하고, 댓글이 지워지면 해당 댓글에 대한 대댓글이 지워져야 한다는 점을 알게되었습니다. 이 때문에 서비스와 레포지토리가 각 역할별로 분리되지 못하고 그물처럼 뭉쳐 있는 다는 말이 정확한 것 같습니다. 추후에 구조 패턴을 사용하여 이를 해결하겠습니다.

2023-05-09 05:51 UTC, Msangwool commented on src/main/java/com/space/haramspring/board/controller/CommentController.java
> +        return ResponseEntity.ok().body(commentService.createComments(commentUploadDto));
개인 프로젝트에서 미리 코드를 작성하고, 실제 프로젝트에 적용하는 과정에서 실수한 부분이 있는 것 같습니다. 수정했습니다.

2023-05-10 14:44 UTC, mookseong approved these changes
코드가 많이 간결해진것 같습니다.  Repository와 Service간 구분이 된게 보입니다.
고생하셨습니다.

2023-05-10 22:32 UTC, merged